AWSTemplateFormatVersion: '2010-09-09'
Description: MicroPay - Repositorios ECR para microservicios Usuarios y Pagos

Resources:

# ----------------------------
# 📦 ECR REPOSITORIOS
# ----------------------------

  ECRUsuarios:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: usuarios
      ImageScanningConfiguration:
        ScanOnPush: true

  ECRPagos:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: pagos
      ImageScanningConfiguration:
        ScanOnPush: true

Outputs:

  ECRUsuariosURI:
    Description: URI del repositorio ECR de Usuarios
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/usuarios"

  ECRPagosURI:
    Description: URI del repositorio ECR de Pagos
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/pagos"
